### ISSUE TITLE
Am I missing something?

### ISSUE THREAD

**Issue by tadg-paul** [chainpoint/chainpoint-cli#24]
Love the idea, but is the project still alive, or just a victim of its own success and backend calendar servers overwhelmed with requests? I only ask as the issues area seems v quiet, and both of my attempts on a Mac M1 and x86 running Linux are the same:

```
$ chainpoint-cli-macos submit 8e985932695c7af7e3c4fc86389a35c0fe40109bbdb7886621540ec204c3dd92
8e985932695c7af7e3c4fc86389a35c0fe40109bbdb7886621540ec204c3dd92 | Unable to submit at this time, try again
```

```
$ chainpoint-cli-linux submit 8e985932695c7af7e3c4fc86389a35c0fe40109bbdb7886621540ec204c3dd92
8e985932695c7af7e3c4fc86389a35c0fe40109bbdb7886621540ec204c3dd92 | Unable to submit at this time, try again
```

The error is a little vague .. can it just not find an active server, or it's hitting a server that's not accepting requests for whatever reason, or something I'm missing in setting this up locally? I don't want to write a script to keep retrying to an already overwhelmed server, or something that just doesn't exist.

**Comment by tigger-developer** [comment]
I noticed the release I had downloaded (2.0) was marked 'Pre-release' so have gone for v1.4.11 instead marked 'latest', but looking less promising :(

```
$ chainpoint-cli-macos-x64 submit 8e985932695c7af7e3c4fc86389a35c0fe40109bbdb7886621540ec204c3dd92
/snapshot/chainpoint-cli/node_modules/chainpoint-client/dist/bundle.js:1
(function (exports, require, module, __filename, __dirname) { !function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t():"function"==typeof define&&define.amd?define("chainpointClient",[],t):"object"==typeof exports?exports.chainpointClient=t():e.chainpointClient=t()}("undefined"!=typeof self?self:this
,function(){return function(e){var t={};function a(r){if(t[r])return t[r].exports;var n=t[r]={i:r,l:!1,exports:{}};return e[r].call(n.exports,n,n.exports,a),n.l=!0,n.exports}return a.m=e,a.c=t,a.d=function(e,t,r){a.o(e,t)||Object.defineProperty(e,t,{configurable:!1,enumerable:!0,get:r})},a.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return a.d(t,"a",t),t},a.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},a.p="",a(a.s=143)}([function(e,t,a){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=function(e){if(!("string"==typeof e||e instan

Error: There seems to be an issue retrieving a list of available nodes. Please try again.
    at $.v.then.p [as _callback] (/snapshot/chainpoint-cli/node_modules/chainpoint-client/dist/bundle.js:1:419075)
    at $.init.t._callback.t.callback.t.callback (/snapshot/chainpoint-cli/node_modules/chainpoint-client/dist/bundle.js:1:694462)
    at emitTwo (events.js:126:13)
    at $.emit (events.js:214:7)
    at $.<anonymous> (/snapshot/chainpoint-cli/node_modules/chainpoint-client/dist/bundle.js:1:707177)
    at emitOne (events.js:116:13)
    at $.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/snapshot/chainpoint-cli/node_modules/chainpoint-client/dist/bundle.js:1:706019)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by jacohend** [comment]
Hi tigger04, https://github.com/chainpoint/chainpoint-js should work best for you. CLI is mostly for a legacy system.
